Rocky/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;

namespace Rocky.Controllers;

public class ApplicationTypeController : Controller
{
    private readonly ApplicationDbContext _db;

    public ApplicationTypeController(ApplicationDbContext db)
    {
        _db = db;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var objList = _db.ApplicationTypes.ToList();
        return View(objList);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(ApplicationType applicationType)
    {
        if (!ModelState.IsValid)
        {
            return View(applicationType);
        }
        else
        {
            _db.Add(applicationType);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

    [HttpGet]
    public IActionResult Edit(int? id)
    {
        if (id == 0 || id == null) return NotFound();
        var obj = _db.ApplicationTypes.Find(id);
        if (obj == null) return NotFound();
        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(ApplicationType obj)
    {
        if (!ModelState.IsValid)
        {
            return View(obj);
        }
        else
        {
            _db.ApplicationTypes.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }


    [HttpGet]
    public IActionResult Delete(int? id)
    {
        if (id == 0 || id == null) return NotFound();
        var applicationType = _db.ApplicationTypes.Find(id);
        if (applicationType == null) return NotFound();
        return View(applicationType);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(ApplicationType obj)
    {
        if (!ModelState.IsValid)
        {
            return View(obj);
        }
        else
        {
            _db.ApplicationTypes.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Rocky/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;

namespace Rocky.Controllers;

public class CategoryController : Controller
{
    private readonly ApplicationDbContext _db;

    public CategoryController(ApplicationDbContext db)
    {
        _db = db;
    }
    [HttpGet]
    public IActionResult Index()
    {
        var objList = _db.Categories.ToList();
        return View(objList);
    }
    [HttpGet]
    public IActionResult Upsert(int? id)
    {
        Category Category = new Category();
        if (id == null)
        {
            return View(Category);
        }
        else
        {
            Category? obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Category category)
    {
        if (!ModelState.IsValid)
        {
            return View(category);
        }
        else
        {
            if (category.Id == 0)
            {
                _db.Categories.Add(category);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                _db.Categories.Update(category);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
    }
    //[HttpGet]
    //public IActionResult Edit(int? id)
    //{
    //    if (id == 0 || id == null) return NotFound();
    //    var category = _db.Categories.Find(id);
    //    if (category == null) return NotFound();
    //    return View(category);
    //}

    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public IActionResult Edit(Category category)
    //{
    //    if (!ModelState.IsValid)
    //    {
    //        return View(category);
    //    }
    //    else
    //    {
    //        _db.Categories.Update(category);
    //        _db.SaveChanges();
    //        return RedirectToAction("Index");
    //    }
    //}


    [HttpGet]
    public IActionResult Delete(int? id)
    {
        if (id == 0 || id == null) return NotFound();
        var category = _db.Categories.Find(id);
        if (category == null) return NotFound();
        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(Category category)
    {
        if (!ModelState.IsValid)
        {
            return View(category);
        }
        else
        {
            _db.Categories.Remove(category);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

Rocky/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rocky.Data;
using Rocky.Models;
using Rocky.ViewModels;

namespace Rocky.Controllers;

public class ProductController : Controller
{
    private readonly ApplicationDbContext _db;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public ProductController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
    {
        _db = db;
        _webHostEnvironment = webHostEnvironment;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var objList = _db.Products.Include(p => p.Category).Include(p => p.ApplicationType).ToList();
        return View(objList);
    }

    [HttpGet]
    public IActionResult Upsert(int? id)
    {
        ProductVM productVM = new ProductVM();
        IEnumerable<SelectListItem> categoryDropDown =
            _db.Categories.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();

        IEnumerable<SelectListItem> applicationTypeDropDown =
    _db.ApplicationTypes.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();

        productVM.CategorySelectList = categoryDropDown;
        productVM.ApplicationTypeSelectList = applicationTypeDropDown;


        if (id == null)
        {
            //Create
            return View(productVM);
        }
        else
        {
            //Update
            productVM.Product = _db.Products.Find(id);
            if (productVM.Product == null)
            {
                return NotFound();
            }
            return View(productVM);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductVM obj)
    {
        if (!ModelState.IsValid)
        {
            return View(obj);
        }
        else
        {
            _db.Products.Update(obj.Product!);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }




    [HttpGet]
    public IActionResult Delete(int? id)
    {
        if (id == 0 || id == null) return NotFound();
        var obj = _db.Products.Find(id);
        if (obj == null) return NotFound();
        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(Product obj)
    {

        _db.Products.Remove(obj);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Rocky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocky</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Rocky.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rocky</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Rocky - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- include summernote css/js -->
    
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>